import Head from 'next/head'
import Header from '../components/Header'
import Jumbotron from '../components/Jumbotron'
import styles from '../styles/Home.module.css'
import  Link  from 'next/link';
import {useContext} from 'react'
import Footer from '../components/Footer';
import Swipers from '../components/Swipers';
import Categorypreview from '../components/Categorypreview';
import Productpreview from '../components/Productpreview';
import ProductDetails from '../components/ProductDetails';
import { GlobalContext } from "../context/Globalcontext";

export default function Home() {
  let {products, categories} = useContext(GlobalContext)

  return (
    <>
      <Head>
        <title>Advanced Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./assets/images/logo.jpg" />
      </Head>
      <Header />
      <Jumbotron />
      <section className={`w-70 w-s-100 margin-auto padding`}>
        <h2 className='curly xx-large text-center'>Available Categories</h2>
        <Categorypreview products={products} categories={categories} />   
      </section>

      <div className={`flex justify-center align-center column padding ${styles.goldenofffer}`}>
        <h3>Golden Offer</h3>
        <h1 className={`${styles.offerh1}`}>GET UP TO 7 DAYS MONEY BACK GUSRSNTEE</h1>
        <button className={`${styles.offerbtn}`}>
            <Link href='/shop' >Shop Now</Link>
        </button>
      </div>

      <section className={`flex justify-around wrap padding ${styles.productpreview}`}>
        <div className={`w-80 w-s-100`}>
            <h2 className=''>PREVIEW PRODUCTS</h2>
            <Productpreview products={products.slice(0, 10)} />   
        </div>
      </section>

      <div className={`flex justify-center align-center column padding ${styles.goldenofffer}`}>
        <h3>Golden Offer</h3>
        <h1 className={`${styles.offerh1}`}>GET UP TO 7 DAYS MONEY BACK GUSRSNTEE</h1>
        <button className={`${styles.offerbtn}`}>
            <Link href='/shop' >Shop Now</Link>
        </button>
      </div>

      <div className={`bluebg`}>
      <section className={`padding`}>
        <h2 className=''>HATS COLLECTION</h2>
        <div className="flex justify-around wrap">
          <div className={`w-60 w-s-100`}>
            <Swipers products={products.filter(prod => prod.category === 'hats')} />
          </div>
            <div className={`flex justify-center `}>
                <img src="./assets/images/logo.jpg" alt="" className={`round`} width='200px' height='200px'/>
            </div>   
        </div>
      </section>
      <section className={`padding`}>
        <h2 className=''>SKIRTS COLLECTION</h2>
        <div className="flex justify-around wrap">
          <div className={`w-60 w-s-100`}>
            <Swipers products={products.filter(prod => prod.category === 'skirts')} />
          </div>
            <div className={`flex justify-center align-center`}>
                <img src="./assets/images/logo.jpg" alt="" className={`round`} width='200px' height='200px'/>
            </div>   
        </div>
      </section>

      </div>
      
      <Footer />
    </>  
  )
}
