import Head from 'next/head'
import styles from '../styles/Product.module.css'
import {useState, useRef, useEffect, useContext} from 'react'
import axios from 'axios'
import {useRouter} from 'next/router'
import {GlobalContext} from '../context/Globalcontext'


const Login = () => {
    const {sever} = useContext(GlobalContext)
    const [email, setemail] = useState('')
    const [password, setpassword] = useState('')
    const submitbtn = useRef()
    const loginUser = async (e) => {
        e.preventDefault()
        let user = {
            email, password
        }
    try {
        const {data} = await axios.post(`https://advancedshoppingsever.herokuapp.com/api/users/signin`, user)
        localStorage.setItem('user', JSON.stringify(data))
         router.push('/dashboard')
    } catch (error) {
        console.log(error)
    }
    }

    const router = useRouter()

    useEffect(() => {
        if (localStorage.getItem('user')) {
            router.push('/dashboard')
        }
    }, [])

    return (
        <>
            <Head>
                <title>login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="./assets/images/logo.jpg" />
            </Head>
            <div className={`bluebg flex align-center justify-center ${styles.shippingaddresss}`}>
                <div>
                    <form className={`flex column ${styles.shippingform}`} onSubmit={loginUser} >
                        <div className={`flex column ${styles.shippingformitem}`}>
                            <label htmlFor="">Email</label>
                            <input type="email" value={email} onChange={e => setemail(e.target.value)} required/>
                        </div>
                        <div className={`flex column ${styles.shippingformitem}`}>
                            <label htmlFor="">Password</label>
                            <input type="password" value={password} onChange={e => setpassword(e.target.value)} required/>
                        </div>
                        <button className={` hide`} ref={submitbtn}>login</button>
                    </form>
                    <button className={`${styles.shippingbtn} pointer bluebg`} onClick={e => submitbtn.current.click()}  >login</button>
                </div>
            </div>
        </>
    );
}


export default Login;