import Header from '../components/Header'
import Productdisplay from '../components/Productdisplay';
import Footer from '../components/Footer';
import styles from '../styles/Product.module.css'
import Head from 'next/head'
import Swipers from '../components/Swipers';
import { useRouter } from "next/dist/client/router";
import { useContext, useEffect, useState } from "react";
import { GlobalContext } from "../context/Globalcontext";
import LoadingBox from '../components/LoadingBox'

const Shop = (props) => {
  const {products} = useContext(GlobalContext)

  const route = useRouter()


    return (
        <>
            <Head>
                <title>shop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="./assets/images/logo.jpg" />
            </Head>
            <Header />
            <section className={`hides`}>
                <div className={`${styles.prodjum} flex justify-center align-center`}>
                        home/shop
                </div>
            </section>
            <Productdisplay />
            
      <div className={`bluebg`}>
      <section className={`padding`}>
        <h2>MOST VIEWED PRODUCTS</h2>
        <div className="flex justify-around wrap">
          <div className={`w-90 w-s-100`}>
          {
            products[0]?
           <Swipers products={products.filter(prod => prod.category === 'skirts')} />
           : <LoadingBox />
           }
          </div>
        </div>
      </section>
      <section className={`padding`}>
        <h2>MOST REVIED RODUCTS</h2>
        <div className="flex justify-around wrap">
          <div className={`w-90 w-s-100`}>
          {
            products[0]?
           <Swipers products={products.filter(prod => prod.category === 't-shirts')} />
           : <LoadingBox />
           }
          </div> 
        </div>
      </section>
      <section className={`padding`}>
        <h2>MOST ORDERD PRODUCTS</h2>
        <div className="flex justify-around wrap">
          <div className={`w-90 w-s-100`}>
          {
            products[0]?
           <Swipers products={products.filter(prod => prod.category === 'shoes')} />
           : <LoadingBox />
           }
          </div> 
        </div>
      </section>

      </div>
      
            <Footer />
        </>
    );
}

// Shop.defaultProps = {
//   data: {
//       products: {
//           title: 'Not the actual data',
//       },
//   },
// };


export default Shop;

// export const getStaticProps = async () => {
//   const sever = 'http://localhsot:5000'
//   const {data} = await axios.get(`${sever}/api/products/other`)
//   const {data: categories} = await axios.get(`${sever}/api/products/categories`)
//   return {
//       props: {
//           products : data || {},
//           categories,
//       }
//   }
// }