import Header from '../components/Header'
import Productdisplay from '../components/Productdisplay';
import Footer from '../components/Footer';
import styles from '../styles/Product.module.css'
import Head from 'next/head'
import Swipers from '../components/Swipers';
import router, { useRouter } from "next/router";
import { useContext, useEffect, useState } from "react";
import { GlobalContext } from "../context/Globalcontext";
import LoadingBox from '../components/LoadingBox'

const Shop = (props) => {
  const {products} = useContext(GlobalContext)
  const [clone1, setclone1] = useState([])
  const [clone2, setclone2] = useState([])
  const [clone3, setclone3] = useState([])
  const route = useRouter()

  useEffect(() => {
    setclone1(products)
    setclone2(products)
    setclone3(products)
  }, [products])


    return (
        <>
            <Head>
                <title>shop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="./assets/images/logo.png" />
                <script src="//code.tidio.co/ftuqj1khsqhmuxgwhvmultjlstv4bcw8.js" async></script>
            </Head>
            <Header />
            <section className={`hides`}>
                <div className={`${styles.prodjum} flex justify-center curly xx-large align-center`}>
                        home/shop
                </div>
            </section>
            <Productdisplay />
            
      <div className={`bluebg`}>
      <section className={`padding`}>
        <h2>MOST REVIEWED PRODUCTS</h2>
        <div className="flex justify-around wrap">
          <div className={`w-90 w-s-100`}>
          {
            products[0]?
           <Swipers products={clone1.sort((a, b) => {
            return b.numReviews - a.numReviews;
        })} />
           : <LoadingBox />
           }
          </div>
        </div>
      </section>
      <section className={`padding`}>
        <h2>MOST REVIED RODUCTS</h2>
        <div className="flex justify-around wrap">
          <div className={`w-90 w-s-100`}>
          {
            products[0]?
           <Swipers products={clone2.sort((a, b) => {
            let older = new Date(a.lastlyreviewed).getTime()
            let newer = new Date(b.lastlyreviewed).getTime()
            return older > newer? -1 : 1
        })} />
           : <LoadingBox />
           }
          </div> 
        </div>
      </section>
      <section className={`padding`}>
        <h2>NEW STOCKS</h2>
        <div className="flex justify-around wrap">
          <div className={`w-90 w-s-100`}>
          {
            products[0]?
           <Swipers products={clone3.sort((a, b) => {
            let older = new Date(a.createdAt).getTime()
            let newer = new Date(b.createdAt).getTime()
            return older > newer? -1 : 1
        })} />
           : <LoadingBox />
           }
          </div> 
        </div>
      </section>

      </div>
      
            <Footer />
        </>
    );
}

// Shop.defaultProps = {
//   data: {
//       products: {
//           title: 'Not the actual data',
//       },
//   },
// };


export default Shop;

// export const getStaticProps = async () => {
//   const sever = 'http://localhsot:5000'
//   const {data} = await axios.get(`${sever}/api/products/other`)
//   const {data: categories} = await axios.get(`${sever}/api/products/categories`)
//   return {
//       props: {
//           products : data || {},
//           categories,
//       }
//   }
// }