
import Head from 'next/head'

const Aboutus = () => {
    return (
        <div>
             <Head>
                <title>aboutus</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="./assets/images/logo.png" />
                <script type="text/javascript" id="hs-script-loader" async defer src="//js-eu1.hs-scripts.com/25151583.js"></script>
            </Head>
        </div>
    )
}

export default Aboutus
