export const products = [
    {
        name:"cool hat",
        image:"./downloded-images/hat10.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"hats",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"hat1",
        image:"./downloded-images/hat2.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"hats",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"hat2",
        image:"./downloded-images/hat3.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"hats",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"hat6",
        image:"./downloded-images/hat7.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"hats",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"hat3",
        image:"./downloded-images/hat1.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"hats",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"coolhat4",
        image:"./downloded-images/hat4.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"hats",
        brand: ' Nike',
        rating: 4.5,
        countInStock: 30,
    },
    {
        name:"hat4",
        image:"./downloded-images/hat5.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"hats",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"hat5",
        image:"./downloded-images/hat6.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"C",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool hat1",
        image:"./downloded-images/hat8.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"hats",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cooler hat2",
        image:"./downloded-images/hat9.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"hats",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"hat2 cool",
        image:"./downloded-images/hat3.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:9.00,
        category:"hats",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe",
        image:"./downloded-images/shoes.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe1",
        image:"./downloded-images/shoes1.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe2",
        image:"./downloded-images/shoes2.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe3",
        image:"./downloded-images/shoes3.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe4",
        image:"./downloded-images/shoes4.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe5",
        image:"./downloded-images/shoes5.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe6",
        image:"./downloded-images/shoes6.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe7",
        image:"./downloded-images/shoes7.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe8",
        image:"./downloded-images/shoes8.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe9",
        image:"./downloded-images/shoes9.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"cool shoe10",
        image:"./downloded-images/shoes10.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:30.00,
        options:[
            {
                name: "size1",
                price: 30,
            },
            {
                name: "size2",
                price: 40,
            },
            {
                name: "size3",
                price: 50,
            }
        ],
        category:"shoes",
        brand: ' Nike',
        countInStock: 30,
    },

    {
        name:"jaket1",
        image:"./downloded-images/jaket1.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:50,
        category:"jackets",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"jaket2",
        image:"./downloded-images/jaket2.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:50,
        category:"jackets",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"jaket3",
        image:"./downloded-images/jaket3.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:50,
        category:"jackets",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"jaket4",
        image:"./downloded-images/jaket4.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:50,
        category:"jackets",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"jaket5",
        image:"./downloded-images/jaket5.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:50,
        category:"jackets",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"jaket6",
        image:"./downloded-images/jaket6.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:50,
        category:"jackets",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"jaket7",
        image:"./downloded-images/jaket7.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:50,
        category:"jackets",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"jaket8",
        image:"./downloded-images/jaket8.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:50,
        category:"jackets",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"jaket9",
        image:"./downloded-images/jaket9.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:50,
        category:"jackets",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"jaket10",
        image:"./downloded-images/jaket10.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:50,
        category:"jackets",
        brand: ' Nike',
        countInStock: 30,
    },
    {
        name:"short1",
        image:"./downloded-images/short1.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short2",
        image:"./downloded-images/short2.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short5",
        image:"./downloded-images/short5.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short3",
        image:"./downloded-images/shorts3.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short4",
        image:"./downloded-images/shorts4.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short6",
        image:"./downloded-images/shorts6.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short7",
        image:"./downloded-images/shorts7.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short8",
        image:"./downloded-images/shorts8.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short9",
        image:"./downloded-images/shorts9.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short10",
        image:"./downloded-images/shorts10.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short11",
        image:"./downloded-images/shorts11.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"short12",
        image:"./downloded-images/shorts12.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:20,
        category:"shorts",
        brand: ' Nike',
        countInStock: 20,
    },
    {
        name:"skirt1",
        image:"./downloded-images/skirt1.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:35.5,
        category:"skirts",
        brand: ' Nike',
        countInStock: 25,
    },
    {
        name:"skirt2",
        image:"./downloded-images/skirt2.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:35.5,
        category:"skirts",
        brand: ' Nike',
        countInStock: 25,
    },
    {
        name:"skirt3",
        image:"./downloded-images/skirt3.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:35.5,
        category:"skirts",
        brand: ' Nike',
        countInStock: 25,
    },
    {
        name:"skirt4",
        image:"./downloded-images/skirt4.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:35.5,
        category:"skirts",
        brand: ' Nike',
        countInStock: 25,
    },
    {
        name:"skirt5",
        image:"./downloded-images/skirt5.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:35.5,
        category:"skirts",
        brand: ' Nike',
        countInStock: 25,
    },
    {
        name:"skirt6",
        image:"./downloded-images/skirt6.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:35.5,
        category:"skirts",
        brand: ' Nike',
        countInStock: 25,
    },
    {
        name:"skirt7",
        image:"./downloded-images/skirt7.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:35.5,
        category:"skirts",
        brand: ' Nike',
        countInStock: 25,
    },
    {
        name:"skirt8",
        image:"./downloded-images/skirt8.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:35.5,
        category:"skirts",
        brand: ' Nike',
        countInStock: 25,
    },
    {
        name:"skirt",
        image:"./downloded-images/skirt.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:35.5,
        category:"skirts",
        brand: ' Nike',
        countInStock: 25,
    },
    {
        name:"skirt10",
        image:"./downloded-images/skirt10.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:35.5,
        category:"skirts",
        brand: ' Nike',
        countInStock: 25,
    },
    {
        name:"t-shirt1",
        image:"./downloded-images/tshit1.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:45.5,
        category:"t-shirts",
        brand: ' Nike',
        countInStock: 22,
    },
    {
        name:"t-shirt2",
        image:"./downloded-images/tshirt2.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:45.5,
        category:"t-shirts",
        brand: ' Nike',
        countInStock: 22,
    },
    {
        name:"t-shirt3",
        image:"./downloded-images/tshirt3.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:45.5,
        category:"t-shirts",
        brand: ' Nike',
        countInStock: 22,
    },
    {
        name:"t-shirt4",
        image:"./downloded-images/tshirt4.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:45.5,
        category:"t-shirts",
        brand: ' Nike',
        countInStock: 22,
    },
    {
        name:"t-shirt5",
        image:"./downloded-images/tshirt5.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:45.5,
        category:"t-shirts",
        brand: ' Nike',
        countInStock: 22,
    },
    {
        name:"t-shirt6",
        image:"./downloded-images/tshirt6.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:45.5,
        category:"t-shirts",
        brand: ' Nike',
        countInStock: 22,
    },
    {
        name:"t-shirt7",
        image:"./downloded-images/tshirt7.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:45.5,
        category:"t-shirts",
        brand: ' Nike',
        countInStock: 22,
    },
    {
        name:"t-shirt8",
        image:"./downloded-images/tshirt8.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:45.5,
        category:"t-shirts",
        brand: ' Nike',
        countInStock: 22,
    },
    {
        name:"t-shirt9",
        image:"./downloded-images/tshirt9.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:45.5,
        category:"t-shirts",
        brand: ' Nike',
        countInStock: 22,
    },
    {
        name:"t-shirt10",
        image:"./downloded-images/tshirt10.jpg",
        description:"The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words.",
        price:45.5,
        category:"t-shirts",
        brand: ' Nike',
        countInStock: 22,
    },
    
]